Repository dev-answer/dev-answer, pull requests merged in 2021-07, with the labels that each got.

#15 relay 초기 환경설정 및 이를 이용한 임시 화면 구현
  client/.eslintrc.js
  client/babel.config.js
  client/package.json
  client/relay.config.js
  client/src/__generated__/ExamplePageQuery.graphql.ts
  client/src/__generated__/Question_question.graphql.ts
  client/src/components/Example/Question.tsx
  client/src/components/Example/index.tsx
  client/src/graphql/index.ts
  client/src/graphql/schema.graphql
  client/src/index.tsx
  client/src/page/ExamplePage.tsx
  client/webpack.config.js
  client/yarn.lock
Labels: frontend👺

#18 CORS 설정 추가
  server/src/app.ts
  server/src/middlewares/cors.ts
Labels: backend👺

#27 로그인 기능 구현
  client/src/App.tsx
  client/src/__generated__/LoginCallbackPageQuery.graphql.ts
  client/src/components/Login/GitHubOAuthAnchor.tsx
  client/src/constants/domain.ts
  client/src/graphql/schema.graphql
  client/src/page/ExamplePage.tsx
  client/src/page/LoginCallbackPage.tsx
  client/src/page/LoginPage.tsx
  server/.gitignore
  server/package.json
  server/src/app.ts
  server/src/db/inMemoryTokenDB.ts
  server/src/services/auth/authResolver.ts
  server/src/services/auth/authType.ts
  server/src/services/index.ts
  server/yarn.lock
Labels: backend👺, feat🔥, frontend👺

#32 GraphqQL Schema gen 커맨드 추가
  client/package.json
  client/src/graphql/schema.graphql
Labels: feat🔥, frontend👺

#34 댓글 보기 기능 구현
  client/src/App.tsx
  client/src/__generated__/CommentPageQuery.graphql.ts
  client/src/__generated__/Comment_comment.graphql.ts
  client/src/components/Example/Comment.tsx
  client/src/graphql/schema.graphql
  client/src/page/CommentPage.tsx
  server/package.json
  server/src/db/comment.json
  server/src/models/commentModel.ts
  server/src/repositories/commentRepository.ts
  server/src/services/comment/commentResolver.ts
  server/src/services/comment/commentType.ts
  server/src/services/index.ts
  server/yarn.lock
Labels: backend👺, feat🔥, frontend👺

#35 Unit TEST 삭제
  client/test/unit/components/Example/Example.test.tsx
Labels: feat🔥

#37 `yarn run gen:schema` 명령어 동작 안하는 문제 해결
  client/package.json
Labels: bug🐛
